import { v4 as uuidv4 } from 'uuid'

export function seedData() {
  const now = new Date()
  const projects = [
    { id: 'proj_ta', name: 'CS 4780 TA Grading', color: '#3949ab' },
    { id: 'proj_job', name: '春招求职', color: '#f57c00' },
    { id: 'proj_research', name: 'Driver-Ped Interaction Study', color: '#00897b' },
    { id: 'proj_dp1', name: 'Design Project 1', color: '#e53935' },
    { id: 'proj_hack', name: 'EmpireHacks 2026', color: '#667eea' },
    { id: 'proj_adapt', name: 'ADAPT Network Challenge', color: '#ab47bc' }
  ]

  const mcpSources = [
    { id: 'mcp_chrome', name: 'Chrome Browser', status: 'connected', icon: '🌐', dataCount: 14 },
    { id: 'mcp_gworkspace', name: 'Google Workspace', status: 'connected', icon: '📧', dataCount: 9 },
    { id: 'mcp_github', name: 'GitHub', status: 'connected', icon: '🐙', dataCount: 6 },
    { id: 'mcp_desktop', name: 'Desktop Commander', status: 'connected', icon: '💻', dataCount: 8 }
  ]

  const nodes = [
    // ===== CS 4780 TA Grading — Data =====
    { id: 'ta_d1', type: 'D', projectId: 'proj_ta', sourcePlatform: 'claude-cowork',
      content: 'Gradescope PDF submissions from 82 students for CS 4780 ML homework — GMM, K-sweep, NLL analysis problems',
      tags: ['gradescope', 'pdf-submissions', 'machine-learning'],
      dtype: 'file', mcpSource: 'chrome', sharedProjects: [],
      createdAt: new Date(now - 86400000 * 3).toISOString() },
    { id: 'ta_d2', type: 'D', projectId: 'proj_ta', sourcePlatform: 'claude-cowork',
      content: 'Session log: 50+ Chrome automation actions — search student, click submission, navigate pages, verify rubric, modify scores on Gradescope',
      tags: ['session-log', 'chrome-automation', 'gradescope'],
      dtype: 'session-note', mcpSource: 'chrome', sharedProjects: [],
      createdAt: new Date(now - 86400000 * 3).toISOString() },
    { id: 'ta_d3', type: 'D', projectId: 'proj_ta', sourcePlatform: 'claude-cowork',
      content: 'K-Sweep NLL reference values: K=1 NLL=-391.8, K=4 NLL=-532.8, K=16 NLL=-547.0, K=32 NLL=-548.5, K=64 NLL=-549.7, K=128 NLL=-548.8',
      tags: ['reference-data', 'nll-values', 'k-sweep'],
      dtype: 'data-extract', mcpSource: null, sharedProjects: [],
      createdAt: new Date(now - 86400000 * 3).toISOString() },
    // ===== CS 4780 TA Grading — Information =====
    { id: 'ta_i1', type: 'I', projectId: 'proj_ta', sourcePlatform: 'claude-cowork',
      content: 'Pattern detected: 5 students lost points on Q7.1/7.2/8.1 for "not assigning pages" when their NLL values and plots were actually correct — false negative grading error',
      tags: ['grading-pattern', 'false-negative', 'rubric-error'],
      dtype: null, mcpSource: null, sharedProjects: [],
      createdAt: new Date(now - 86400000 * 2).toISOString() },
    { id: 'ta_i2', type: 'I', projectId: 'proj_ta', sourcePlatform: 'claude-cowork',
      content: 'Progress tracking: 5 students × 5 questions each need rubric corrections. Yutong Wang and Chien-Wei Wang fully corrected; Kendall Miller, Hsin-Yu Tsai, Ammar Syed partially done',
      tags: ['progress-tracking', 'rubric-correction', 'status-report'],
      dtype: null, mcpSource: null, sharedProjects: [],
      createdAt: new Date(now - 86400000 * 2).toISOString() },
    // ===== CS 4780 TA Grading — Knowledge =====
    { id: 'ta_k1', type: 'K', projectId: 'proj_ta', sourcePlatform: 'claude-cowork',
      content: 'Skill: verify-before-penalize — When grading at scale, always verify actual content exists before applying structural penalties. PDF page assignment ≠ content absence',
      tags: ['skill', 'grading-methodology', 'cross-domain'],
      dtype: null, mcpSource: null, sharedProjects: ['proj_research'],
      createdAt: new Date(now - 86400000 * 1).toISOString() },
    { id: 'ta_k2', type: 'K', projectId: 'proj_ta', sourcePlatform: 'claude-cowork',
      content: 'Skill: browser-automation-for-repetitive-tasks — Chrome MCP can automate Gradescope grading: search→click→scroll→verify→modify rubric. Saves ~2min per student per question',
      tags: ['skill', 'automation', 'chrome-mcp'],
      dtype: null, mcpSource: 'chrome', sharedProjects: ['proj_job'],
      createdAt: new Date(now - 86400000 * 1).toISOString() },
    // ===== 春招求职 — Data =====
    { id: 'job_d1', type: 'D', projectId: 'proj_job', sourcePlatform: 'claude-cowork',
      content: '748 raw job listings scraped from Geely (吉利) campus recruitment — 29 pages of positions across all departments',
      tags: ['web-scraping', 'geely', 'campus-recruitment'],
      dtype: 'scraped-data', mcpSource: 'chrome', sharedProjects: [],
      createdAt: new Date(now - 86400000 * 5).toISOString() },
    { id: 'job_d2', type: 'D', projectId: 'proj_job', sourcePlatform: 'claude-cowork',
      content: 'Google Sheets created via Workspace MCP: formatted spreadsheets with hyperlinks, job descriptions, department info, and location data',
      tags: ['google-sheets', 'mcp-source:workspace', 'structured-data'],
      dtype: 'mcp-data', mcpSource: 'gworkspace', sharedProjects: [],
      createdAt: new Date(now - 86400000 * 5).toISOString() },
    { id: 'job_d3', type: 'D', projectId: 'proj_job', sourcePlatform: 'claude-cowork',
      content: 'User resume profile: Cornell Tech MS (Connective Media, 4.0 GPA), CHI/AutomotiveUI publications, Stanford/Tsinghua research, HCI + AI focus',
      tags: ['resume', 'profile', 'matching-input'],
      dtype: 'user-profile', mcpSource: null, sharedProjects: ['proj_hack'],
      createdAt: new Date(now - 86400000 * 6).toISOString() },
    // ===== 春招求职 — Information =====
    { id: 'job_i1', type: 'I', projectId: 'proj_job', sourcePlatform: 'claude-cowork',
      content: 'After dedup and sales-filter: 748→700 unique→678 valid positions. 28 recommended (16 ⭐⭐⭐ high match + 12 ⭐⭐ medium match). Best matches: UX, user research, HMI, VR design roles',
      tags: ['analysis-result', 'recommendation', 'filtering'],
      dtype: null, mcpSource: null, sharedProjects: [],
      createdAt: new Date(now - 86400000 * 4).toISOString() },
    { id: 'job_i2', type: 'I', projectId: 'proj_job', sourcePlatform: 'claude-cowork',
      content: 'Pattern: HCI-adjacent roles in automotive (Geely) are abundant — 整车用户体验、用户调研、人机交互、VR设计、HMI项目管理 all highly relevant to user background',
      tags: ['industry-insight', 'hci-automotive', 'career-pattern'],
      dtype: null, mcpSource: null, sharedProjects: [],
      createdAt: new Date(now - 86400000 * 4).toISOString() },
    // ===== 春招求职 — Knowledge =====
    { id: 'job_k1', type: 'K', projectId: 'proj_job', sourcePlatform: 'claude-cowork',
      content: 'Skill: job-scraping-pipeline — Scrape career pages → deduplicate → filter irrelevant (sales) → match against resume → rank by fit → output to Google Sheets with hyperlinks',
      tags: ['skill', 'workflow', 'automation'],
      dtype: null, mcpSource: null, sharedProjects: [],
      createdAt: new Date(now - 86400000 * 3).toISOString() },

    // ===== Driver-Ped Research — Data =====
    { id: 'res_d1', type: 'D', projectId: 'proj_research', sourcePlatform: 'claude-cowork',
      content: '31 participants, 12,558 raw records from lab NAS — driver-pedestrian interaction study with Likert scales + categorical variables from questionnaires',
      tags: ['experiment-data', 'nas-storage', 'raw-data'],
      dtype: 'research-data', mcpSource: 'desktop', sharedProjects: [],
      createdAt: new Date(now - 86400000 * 4).toISOString() },
    { id: 'res_d2', type: 'D', projectId: 'proj_research', sourcePlatform: 'claude-cowork',
      content: 'Python analysis pipeline: pandas + scipy + statsmodels LMM. Processed inclusion criteria (both parties noticed each other), excluded 19 trials, retained 289 valid trials',
      tags: ['python-analysis', 'data-processing', 'statistical-methods'],
      dtype: 'code-analysis', mcpSource: 'desktop', sharedProjects: [],
      createdAt: new Date(now - 86400000 * 4).toISOString() },
    // ===== Driver-Ped Research — Information =====
    { id: 'res_i1', type: 'I', projectId: 'proj_research', sourcePlatform: 'claude-cowork',
      content: 'Key finding: Right of Way agreement only 19.4% (χ²=52.86, p<0.001). "Who Entered First" agreement only 11.5% (χ²=196.33, p<0.001). Drivers and pedestrians fundamentally disagree on interaction dynamics',
      tags: ['statistical-finding', 'chi-squared', 'perception-gap'],
      dtype: null, mcpSource: null, sharedProjects: [],
      createdAt: new Date(now - 86400000 * 3).toISOString() },
    { id: 'res_i2', type: 'I', projectId: 'proj_research', sourcePlatform: 'claude-cowork',
      content: 'Drivers significantly more stressed than pedestrians (M=3.59 vs 4.08, p<0.001, d=-0.41). Shared space scenarios create highest cognitive load and lowest relaxation for both parties',
      tags: ['likert-analysis', 'lmm-result', 'stress-finding'],
      dtype: null, mcpSource: null, sharedProjects: [],
      createdAt: new Date(now - 86400000 * 3).toISOString() },
    { id: 'res_i3', type: 'I', projectId: 'proj_research', sourcePlatform: 'claude-cowork',
      content: 'Data quality issue: Likert text labels did not match preset mapping. Fix: used AnswerId (1-5) directly as numeric values instead of text parsing. Speed perception scales differ between roles — cannot compare directly',
      tags: ['data-quality', 'methodology-fix', 'lessons-learned'],
      dtype: null, mcpSource: null, sharedProjects: [],
      createdAt: new Date(now - 86400000 * 3).toISOString() },
    // ===== Driver-Ped Research — Knowledge =====
    { id: 'res_k1', type: 'K', projectId: 'proj_research', sourcePlatform: 'claude-cowork',
      content: 'Skill: always-check-raw-labels — When analyzing Likert data, always inspect actual response text before mapping. Preset mappings often mismatch survey implementations. Use numeric IDs when available',
      tags: ['skill', 'data-analysis', 'methodology'],
      dtype: null, mcpSource: null, sharedProjects: ['proj_ta'],
      createdAt: new Date(now - 86400000 * 2).toISOString() },
    { id: 'res_k2', type: 'K', projectId: 'proj_research', sourcePlatform: 'claude-cowork',
      content: 'Skill: structured-analysis-report — Present statistical results with effect sizes (Cohen d), confidence intervals, and scenario breakdowns. Always pair p-values with practical significance',
      tags: ['skill', 'academic-writing', 'statistics'],
      dtype: null, mcpSource: null, sharedProjects: [],
      createdAt: new Date(now - 86400000 * 2).toISOString() },

    // ===== Design Project 1 — Data =====
    { id: 'dp1_d1', type: 'D', projectId: 'proj_dp1', sourcePlatform: 'claude-cowork',
      content: 'Google Doc design report with images: sketch_clean.png, Fusion 360 screenshots, Bambu Studio prints, failed red print photos. Doc ID: 1a7UGPbLUi6DvKbuIu_aeGbrBc-G2Y757j3rebxoq22g',
      tags: ['google-doc', 'design-report', 'images'],
      dtype: 'file', mcpSource: 'gworkspace', sharedProjects: [],
      createdAt: new Date(now - 86400000 * 6).toISOString() },
    { id: 'dp1_d2', type: 'D', projectId: 'proj_dp1', sourcePlatform: 'claude-cowork',
      content: 'Session log: fixed missing first paragraph, inserted sketch image, added Figure captions (Fig 1, 3, 4). Multiple Google Workspace MCP calls for doc inspection and modification',
      tags: ['session-log', 'doc-editing', 'mcp-source:workspace'],
      dtype: 'session-note', mcpSource: 'gworkspace', sharedProjects: [],
      createdAt: new Date(now - 86400000 * 6).toISOString() },
    // ===== Design Project 1 — Information =====
    { id: 'dp1_i1', type: 'I', projectId: 'proj_dp1', sourcePlatform: 'claude-cowork',
      content: 'Design insight: 608 bearing enables extremely smooth low-friction rotation → YoYo concept. Design started from physical constraint, not aesthetic goal. Iterative 3D printing with failures informed final form',
      tags: ['design-insight', 'mechanical-design', 'iteration'],
      dtype: null, mcpSource: null, sharedProjects: [],
      createdAt: new Date(now - 86400000 * 5).toISOString() },
    // ===== Design Project 1 — Knowledge =====
    { id: 'dp1_k1', type: 'K', projectId: 'proj_dp1', sourcePlatform: 'claude-cowork',
      content: 'Skill: doc-image-management — When editing Google Docs with images, always verify images are present after edits (not just captions). Workspace MCP insert_doc_image + inspect_doc_structure is the reliable workflow',
      tags: ['skill', 'google-docs', 'image-handling'],
      dtype: null, mcpSource: 'gworkspace', sharedProjects: [],
      createdAt: new Date(now - 86400000 * 5).toISOString() },

    // ===== EmpireHacks 2026 — Data =====
    { id: 'hack_d1', type: 'D', projectId: 'proj_hack', sourcePlatform: 'claude-cowork',
      content: 'EmpireHacks 2026 application form: Track 3 — agentic AI solutions for real-world workflows. 48-hour hackathon, demo video required, judging rubric from Slack',
      tags: ['hackathon', 'application', 'track-3'],
      dtype: 'file', mcpSource: 'chrome', sharedProjects: [],
      createdAt: new Date(now - 86400000 * 8).toISOString() },
    { id: 'hack_d2', type: 'D', projectId: 'proj_hack', sourcePlatform: 'claude-cowork',
      content: 'User profile scraped from changxiang-scu.github.io: CHI + AutomotiveUI publications, Stanford/Tsinghua research, Cornell Tech MS 4.0 GPA, LLM-powered LaTeX IDE, multi-agent robotics (AAAI under review)',
      tags: ['profile', 'github-pages', 'academic-background'],
      dtype: 'scraped-data', mcpSource: 'chrome', sharedProjects: ['proj_job'],
      createdAt: new Date(now - 86400000 * 8).toISOString() },
    // ===== EmpireHacks 2026 — Information =====
    { id: 'hack_i1', type: 'I', projectId: 'proj_hack', sourcePlatform: 'claude-cowork',
      content: 'Application strategy: highlight intersection of HCI research depth (CHI/AutomotiveUI) + AI building ability (LLM tools, multi-agent) + unique human-in-the-loop perspective. Emphasize agentic systems that are genuinely usable',
      tags: ['strategy', 'application-writing', 'positioning'],
      dtype: null, mcpSource: null, sharedProjects: [],
      createdAt: new Date(now - 86400000 * 7).toISOString() },
    // ===== EmpireHacks 2026 — Knowledge =====
    { id: 'hack_k1', type: 'K', projectId: 'proj_hack', sourcePlatform: 'claude-cowork',
      content: 'Skill: hackathon-scoping — Under 48hr constraint: identify ONE killer demo flow → polish it → skip everything else. For Mnemosyne: focus on mind-palace graph UI as the hero feature',
      tags: ['skill', 'project-management', 'hackathon'],
      dtype: null, mcpSource: null, sharedProjects: [],
      createdAt: new Date(now - 86400000 * 7).toISOString() },

    // ===== ADAPT Network Challenge — Data =====
    { id: 'adapt_d1', type: 'D', projectId: 'proj_adapt', sourcePlatform: 'claude-cowork',
      content: 'ADAPT Network challenge brief: design for actors with disabilities, especially Cerebral Palsy. Form fields: stakeholders, key question, need statement',
      tags: ['design-challenge', 'accessibility', 'form-data'],
      dtype: 'file', mcpSource: 'chrome', sharedProjects: [],
      createdAt: new Date(now - 86400000 * 2).toISOString() },
    // ===== ADAPT Network Challenge — Information =====
    { id: 'adapt_i1', type: 'I', projectId: 'proj_adapt', sourcePlatform: 'claude-cowork',
      content: 'Three key stakeholders identified: (1) Actors with disabilities, especially CP, (2) ADAPT staff and caregivers, (3) Director and creative team. Core need: device-free script navigation to reduce physical fatigue',
      tags: ['stakeholder-analysis', 'need-finding', 'accessibility'],
      dtype: null, mcpSource: null, sharedProjects: [],
      createdAt: new Date(now - 86400000 * 1).toISOString() },
    { id: 'adapt_i2', type: 'I', projectId: 'proj_adapt', sourcePlatform: 'claude-cowork',
      content: 'Need statement: Actors with CP need a way to navigate scripts and operate devices without relying on repetitive hand movements so they can rehearse independently and focus on performance',
      tags: ['need-statement', 'design-brief', 'human-centered'],
      dtype: null, mcpSource: null, sharedProjects: [],
      createdAt: new Date(now - 86400000 * 1).toISOString() },
    // ===== Cross-project Wisdom =====
    { id: 'w1', type: 'W', projectId: 'proj_research', sourcePlatform: 'claude-cowork',
      content: 'CLAUDE.md: In human interaction studies, communication inconsistency is the norm — unlike controlled AV studies. Always design for ambiguity, not consensus. This applies to UX research, TA feedback, and team collaboration',
      tags: ['meta-rule', 'research-wisdom', 'design-principle'],
      dtype: null, mcpSource: null, sharedProjects: ['proj_ta', 'proj_adapt'],
      createdAt: new Date(now - 86400000 * 1).toISOString() },
    { id: 'w2', type: 'W', projectId: 'proj_hack', sourcePlatform: 'claude-cowork',
      content: 'CLAUDE.md: MCP tools are force multipliers — Chrome for web automation, Workspace for doc management, Desktop Commander for local processing. Chain them for complex workflows. But always verify outputs at each step',
      tags: ['meta-rule', 'tool-philosophy', 'mcp-wisdom'],
      dtype: null, mcpSource: null, sharedProjects: ['proj_ta', 'proj_job', 'proj_research'],
      createdAt: new Date(now - 86400000 * 1).toISOString() },
    { id: 'w3', type: 'W', projectId: 'proj_job', sourcePlatform: 'claude-cowork',
      content: 'CLAUDE.md: User works inside-out — tackles core substance first, then framing. For code: fix logic before style. For essays: evidence before intro. For job search: match skills before polishing resume. Adapt assistance order accordingly',
      tags: ['meta-rule', 'user-preference', 'work-style'],
      dtype: null, mcpSource: null, sharedProjects: ['proj_dp1', 'proj_adapt'],
      createdAt: new Date(now - 86400000 * 1).toISOString() },
  ]

  const connections = [
    // TA Grading: D→I→K
    { id: 'c1', fromNodeId: 'ta_d1', toNodeId: 'ta_i1', label: 'revealed pattern' },
    { id: 'c2', fromNodeId: 'ta_d2', toNodeId: 'ta_i2', label: 'logged progress' },
    { id: 'c3', fromNodeId: 'ta_d3', toNodeId: 'ta_i1', label: 'validated against' },
    { id: 'c4', fromNodeId: 'ta_i1', toNodeId: 'ta_k1', label: 'generalizes to' },
    { id: 'c5', fromNodeId: 'ta_i2', toNodeId: 'ta_k2', label: 'generalizes to' },
    // Job Search: D→I→K
    { id: 'c6', fromNodeId: 'job_d1', toNodeId: 'job_i1', label: 'filtered into' },
    { id: 'c7', fromNodeId: 'job_d2', toNodeId: 'job_i1', label: 'structured as' },
    { id: 'c8', fromNodeId: 'job_d3', toNodeId: 'job_i2', label: 'matched against' },
    { id: 'c9', fromNodeId: 'job_i1', toNodeId: 'job_k1', label: 'generalizes to' },
    { id: 'c10', fromNodeId: 'job_i2', toNodeId: 'job_k1', label: 'reinforces' },
    // Research: D→I→K
    { id: 'c11', fromNodeId: 'res_d1', toNodeId: 'res_i1', label: 'analyzed into' },
    { id: 'c12', fromNodeId: 'res_d2', toNodeId: 'res_i2', label: 'produced' },
    { id: 'c13', fromNodeId: 'res_d2', toNodeId: 'res_i3', label: 'uncovered issue' },
    { id: 'c14', fromNodeId: 'res_i1', toNodeId: 'res_k2', label: 'generalizes to' },
    { id: 'c15', fromNodeId: 'res_i3', toNodeId: 'res_k1', label: 'generalizes to' },
    // DP1: D→I→K
    { id: 'c16', fromNodeId: 'dp1_d1', toNodeId: 'dp1_i1', label: 'documented in' },
    { id: 'c17', fromNodeId: 'dp1_d2', toNodeId: 'dp1_k1', label: 'generalizes to' },
    // Hackathon: D→I→K
    { id: 'c18', fromNodeId: 'hack_d1', toNodeId: 'hack_i1', label: 'informed' },
    { id: 'c19', fromNodeId: 'hack_d2', toNodeId: 'hack_i1', label: 'sourced from' },
    { id: 'c20', fromNodeId: 'hack_i1', toNodeId: 'hack_k1', label: 'generalizes to' },
    // ADAPT: D→I
    { id: 'c21', fromNodeId: 'adapt_d1', toNodeId: 'adapt_i1', label: 'analyzed into' },
    { id: 'c22', fromNodeId: 'adapt_i1', toNodeId: 'adapt_i2', label: 'synthesized into' },
    // Cross-project → Wisdom
    { id: 'c23', fromNodeId: 'res_k1', toNodeId: 'w1', label: 'evolves into' },
    { id: 'c24', fromNodeId: 'res_k2', toNodeId: 'w1', label: 'evolves into' },
    { id: 'c25', fromNodeId: 'ta_k2', toNodeId: 'w2', label: 'evolves into' },
    { id: 'c26', fromNodeId: 'job_k1', toNodeId: 'w2', label: 'evolves into' },
    { id: 'c27', fromNodeId: 'hack_k1', toNodeId: 'w3', label: 'evolves into' },
    // Cross-project reinforcements
    { id: 'c28', fromNodeId: 'ta_k1', toNodeId: 'res_k1', label: 'reinforces' },
    { id: 'c29', fromNodeId: 'job_d3', toNodeId: 'hack_d2', label: 'same source' },
    { id: 'c30', fromNodeId: 'adapt_i2', toNodeId: 'w1', label: 'reinforces' },
  ]

  return { projects, mcpSources, nodes, connections }
}
